google_sheets_script/google_sheets_script/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sheets_app.urls', namespace='sheets_app')),
]

google_sheets_script/sheets_app/urls.py
from django.urls import path

from . import views


app_name = 'sheets_app'

urlpatterns = [
    path('', views.index, name='index'),
]

google_sheets_script/sheets_app/models.py
from django.db import models


class Orders(models.Model):
    """
    Model to add to the database
     values from Google spreadsheet:
     №, order №, order value in $ and RUB, delivery time.
    """
    number = models.PositiveSmallIntegerField(
        verbose_name='№', unique=True
        )
    order_number = models.PositiveIntegerField(
        verbose_name='Order №', primary_key=True
        )
    price_usd = models.PositiveIntegerField(
        verbose_name='Price,$'
        )
    price_rub = models.FloatField(
        verbose_name='Price,RUB'
        )
    shipping_date = models.DateTimeField(
        verbose_name='Delivery date'
        )

    def __str__(self) -> str:
        return "Order №" + str(self.order_number)

google_sheets_script/sheets_app/views.py
from django.shortcuts import render

from .models import Orders


def index(request):
    """View function for processing the main page of the site"""
    orders = Orders.objects.all()

    context = {
        'orderlines': orders,
        }
    return render(request, 'sheets_app/index.html', context)

google_sheets_script/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Google sheets to PostgreSQL</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: white">
        <div class="container">
          <a class="navbar-brand" href="{% url 'sheets_app:index' %}">
            <img src="{% static 'img/logo_1.png' %}" width="100" height="80" class="d-inline-block align-top" alt="">
          </a>
        </div>
      </nav> 
    </header>
    <main>
        {% block content %}
          Ошибка загрузки контента 
        {% endblock %}
      </main>
    <footer class="border-top text-center py-3">
      <p>© 2023 Copyright</p> 
    </footer>  
  </body>
</html> 

google_sheets_script/templates/sheets_app/index.html
{% extends 'base.html' %}
{% block content %}
<main>
  <div class="row col-12">
    <div class="row col-1">
    </div>
    <div class="col-6">
      <table class="table">
        <tbody>
          <tr>
            <th>№</th>
            <th>Order №</th>
            <th>Price,$</th>
            <th>Price,RUB</th>
            <th>Delivery date</th>
          </tr>
          {% for orderline in orderlines %}
          <tr>
            <td>{{ orderline.number }}</td>
            <td>{{ orderline.order_number }}</td>
            <td>{{ orderline.price_usd }}</td>
            <td>{{ orderline.price_rub }}</td>
            <td>{{ orderline.shipping_date|date:"j.m.Y" }}</td>
          </tr>
          {% endfor %} 
        </tbody> 
      </table>
    <div class="row col-4">
    </div>
    <div class="row col-1">
    </div>
    </div>
  </div>
</main>
{% endblock %}